Create idk.py
So I am pulling CDC COVID data and I am having a hard time getting the data into a database. When I run my code I get this traceback: 

C:\Users\micha\Documents\py4e\IDK\idk.py:39: SyntaxWarning: 'str' object is not callable; perhaps you missed a comma?
  cur.execute('''INSERT INTO CState(State, Count) VALUES(?,?)'''(memoryview(state_data.encode())))
C:\Users\micha\Documents\py4e\IDK\idk.py:40: SyntaxWarning: 'str' object is not callable; perhaps you missed a comma?
  cur.execute('''INSERT INTO CDate(Date, Count) VALUES(?,?)'''(memoryview(date_data.encode())))
Traceback (most recent call last):
  File "C:\Users\micha\Documents\py4e\IDK\idk.py", line 28, in <module>
    cur.execute("SELECT Date FROM CDate WHERE Count= ?",(memoryview(date_data.encode()), ))
AttributeError: 'list' object has no attribute 'encode'

and I am not sure what it means or what I am doing wrong. 

Here is my code, if someone could please look at it tell me what I am missing.